version: "3.9"
services:
  mysql:
    image: mysql:8.0
    hostname: trevari
    container_name: trevari-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_DATABASE: trevari
      MYSQL_USER: trevari
      MYSQL_PASSWORD: trevari1234
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql/config:/etc/mysql/conf.d
      - ./database/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - network

  redis:
    image: redis:6.2.6-alpine
    container_name: trevari-redis
    ports:
      - "16379:6379"
    networks:
      - network

  app:
    build: .
    container_name: trevari-app
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trevari?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: trevari
      SPRING_DATASOURCE_PASSWORD: trevari1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - network
networks:
  network:
    driver: bridge
